[package]
name = "pallet-mt-rpc-runtime-api"
version = "1.0.0"
authors = ["Webb"]
edition = "2018"
license = "Apache-2.0"
description = "RPC runtime API for merkle tree pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17" }
pallet-mt = { default-features = false, path = "../../" }
webb-primitives = { path = "../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"pallet-mt/std",
	"webb-primitives/std",
]
