[package]
authors = ["Webb"]
description = "RPC runtime API for merkle tree pallet"
edition = "2018"
license = "Apache-2.0"
name = "pallet-mt-rpc-runtime-api"
readme = "README.md"
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }
webb-primitives = { path = "../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
  "sp-api/std",
  "webb-primitives/std",
]
