// This file is part of Webb.

// Copyright (C) 2022 Webb Technologies Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_mixer
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-06-14, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: ``, CPU: ``
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/webb-standalone-node
// benchmark
// pallet
// --chain=dev
// --steps=20
// --repeat=10
// --log=warn
// --pallet=pallet-mixer
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/mixer/src/weights.rs
// --template=./.maintain/webb-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn create(d:u32) -> Weight;
	fn deposit() -> Weight;
	fn withdraw() -> Weight;
}

/// Weight functions for `pallet_mixer`.
pub struct WebbWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for WebbWeight<T> {
	// Storage: MerkleTree NextTreeId (r:1 w:1)
	// Storage: MerkleTree DefaultHashes (r:1 w:0)
	// Storage: Mixer Mixers (r:0 w:1)
	// Storage: MerkleTree Trees (r:0 w:1)
	fn create(d: u32, ) -> Weight {
		(34_099_000 as Weight)
			// Standard Error: 5_000
			.saturating_add(43_000_u64.saturating_mul(d as Weight))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// Storage: MerkleTree Trees (r:1 w:1)
	// Storage: MerkleTree DefaultHashes (r:1 w:0)
	// Storage: BN254CircomPoseidon3x5Hasher Parameters (r:1 w:0)
	// Storage: MerkleTree NextRootIndex (r:1 w:1)
	// Storage: MerkleTree NextLeafIndex (r:1 w:1)
	// Storage: Mixer Mixers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: MerkleTree Leaves (r:0 w:1)
	// Storage: MerkleTree CachedRoots (r:0 w:1)
	fn deposit() -> Weight {
		(9_847_660_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	// Storage: Mixer Mixers (r:1 w:0)
	// Storage: MerkleTree Trees (r:1 w:0)
	// Storage: MerkleTree CachedRoots (r:1 w:0)
	// Storage: Mixer NullifierHashes (r:1 w:1)
	// Storage: MixerVerifier Parameters (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	fn withdraw() -> Weight {
		(35_264_966_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

impl WeightInfo for () {
	// Storage: MerkleTree NextTreeId (r:1 w:1)
	// Storage: MerkleTree DefaultHashes (r:1 w:0)
	// Storage: Mixer Mixers (r:0 w:1)
	// Storage: MerkleTree Trees (r:0 w:1)
	fn create(d: u32, ) -> Weight {
		(34_099_000 as Weight)
			// Standard Error: 5_000
			.saturating_add(43_000_u64.saturating_mul(d as Weight))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// Storage: MerkleTree Trees (r:1 w:1)
	// Storage: MerkleTree DefaultHashes (r:1 w:0)
	// Storage: BN254CircomPoseidon3x5Hasher Parameters (r:1 w:0)
	// Storage: MerkleTree NextRootIndex (r:1 w:1)
	// Storage: MerkleTree NextLeafIndex (r:1 w:1)
	// Storage: Mixer Mixers (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: MerkleTree Leaves (r:0 w:1)
	// Storage: MerkleTree CachedRoots (r:0 w:1)
	fn deposit() -> Weight {
		(9_847_660_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	// Storage: Mixer Mixers (r:1 w:0)
	// Storage: MerkleTree Trees (r:1 w:0)
	// Storage: MerkleTree CachedRoots (r:1 w:0)
	// Storage: Mixer NullifierHashes (r:1 w:1)
	// Storage: MixerVerifier Parameters (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	fn withdraw() -> Weight {
		(35_264_966_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
