[package]
name = "pallet-linkable-tree-rpc-runtime-api"
version = "1.0.0"
authors = ["Webb"]
edition = "2018"
license = "Apache-2.0"
description = "Linkable tree RPC API for linkable tree pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }
pallet-linkable-tree = { default-features = false, path = "../../" }
webb-primitives = { path = "../../../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"pallet-linkable-tree/std",
	"webb-primitives/std",
]
