// This file is part of Webb.

// Copyright (C) 2022 Webb Technologies Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_signature_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-06-14, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: ``, CPU: ``
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/webb-standalone-node
// benchmark
// pallet
// --chain=dev
// --steps=20
// --repeat=10
// --log=warn
// --pallet=pallet-signature-bridge
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./pallets/signature-bridge/src/weights.rs
// --template=./.maintain/webb-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_signature_bridge.
pub trait WeightInfo {
	fn set_maintainer() -> Weight;
	fn force_set_maintainer() -> Weight;
	fn set_resource() -> Weight;
	fn remove_resource() -> Weight;
	fn whitelist_chain() -> Weight;
	fn set_resource_with_signature() -> Weight;
	fn execute_proposal() -> Weight;
}

/// Weights for pallet_signature_bridge using the Substrate node and recommended hardware.
pub struct WebbWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for WebbWeight<T> {
	// Storage: SignatureBridge Maintainer (r:1 w:1)
	// Storage: SignatureBridge MaintainerNonce (r:1 w:1)
	fn set_maintainer() -> Weight {
		(52_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: SignatureBridge Maintainer (r:1 w:1)
	fn force_set_maintainer() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge Resources (r:0 w:1)
	fn set_resource() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge Resources (r:0 w:1)
	fn remove_resource() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge ChainNonces (r:1 w:1)
	fn whitelist_chain() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge ProposalNonce (r:1 w:1)
	// Storage: SignatureBridge Maintainer (r:1 w:0)
	// Storage: SignatureBridge ChainNonces (r:1 w:0)
	// Storage: SignatureBridge Resources (r:1 w:1)
	fn set_resource_with_signature() -> Weight {
		(61_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: SignatureBridge ProposalNonce (r:1 w:1)
	// Storage: SignatureBridge Maintainer (r:1 w:0)
	// Storage: SignatureBridge ChainNonces (r:1 w:0)
	// Storage: SignatureBridge Resources (r:1 w:0)
	fn execute_proposal() -> Weight {
		(59_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: SignatureBridge Maintainer (r:1 w:1)
	// Storage: SignatureBridge MaintainerNonce (r:1 w:1)
	fn set_maintainer() -> Weight {
		(52_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: SignatureBridge Maintainer (r:1 w:1)
	fn force_set_maintainer() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge Resources (r:0 w:1)
	fn set_resource() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge Resources (r:0 w:1)
	fn remove_resource() -> Weight {
		(1_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge ChainNonces (r:1 w:1)
	fn whitelist_chain() -> Weight {
		(11_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: SignatureBridge ProposalNonce (r:1 w:1)
	// Storage: SignatureBridge Maintainer (r:1 w:0)
	// Storage: SignatureBridge ChainNonces (r:1 w:0)
	// Storage: SignatureBridge Resources (r:1 w:1)
	fn set_resource_with_signature() -> Weight {
		(61_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: SignatureBridge ProposalNonce (r:1 w:1)
	// Storage: SignatureBridge Maintainer (r:1 w:0)
	// Storage: SignatureBridge ChainNonces (r:1 w:0)
	// Storage: SignatureBridge Resources (r:1 w:0)
	fn execute_proposal() -> Weight {
		(59_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}