[package]
name = "pallet-mt-rpc"
version = "0.1.0"
authors = ["Webb Tools"]
edition = "2018"

[dependencies]
jsonrpsee = { version = "0.13.0", features = ["server"] }
thiserror = "1.0"
sc-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }

codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.22" }

webb-primitives = { path = "../../../primitives", default-features = false }
pallet-mt = { path = "../", default-features = false }
pallet-mt-rpc-runtime-api = { path = "./runtime-api", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "webb-primitives/std",
    "pallet-mt/std",
    "pallet-mt-rpc-runtime-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-api/std"
]