[package]
name = "zk-benchmark-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.11"}
ark-serialize = { version = "^0.3.0", default-features = false, features = [ "derive" ]}
ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bn254 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
arkworks-gadgets = { version = "^0.3", features = ["default_poseidon"] }

[workspace]